import assert from "node:assert/strict";
import { emptyGrowthDiscovery, growthProspectsCsv, type GrowthSearchPlan } from "@/lib/growth-discovery";
import { draftOutreach, groundedEvidence, mutateSearchPlan, normalizeAudiences, normalizeProspect, normalizeSearchPlan, readDiscoveryState } from "../growth-discovery-core";
import { publicWebDiscovery, runGrowthDiscovery, type GrowthDiscoveryDependencies, type ProspectDiscoveryProvider } from "../growth-discovery-service";
import type { IntelligenceRequest, IntelligenceResponse } from "@/lib/server/intelligence/intelligence-contract";

const cases: Array<[string, () => void | Promise<void>]> = [];
const test = (name: string, run: () => void | Promise<void>) => cases.push([name, run]);
const plan = normalizeSearchPlan({ titles: ["Art Advisor", "Art Consultant", "Art Acquisition Director"], adjacentTitles: ["Art Advisor", "Collection Manager"], excludedTitles: ["Art Director"], organizationTypes: ["art advisory firms", "hospitality groups"], geographies: ["United States", "Europe"], seniority: ["manager+"], buyingSignals: ["contemporary fine art"], companyCriteria: "Acquisition for high-net-worth clients", limit: 10 });
const quote = "Example Advisory sources contemporary fine art for collectors in Germany.";
const page = { url: "https://example-advisory.test/about", title: "Example Advisory", content: `${quote} We are independent art advisory firms serving private collectors.`, retrievedAt: "2026-09-04T00:00:00Z" };
const candidate = { isCompany: true, excluded: false, name: "Example Advisory", location: "Germany", organizationType: "art advisory firms", evidence: [{ field: "location", quote }, { field: "organizationType", quote: "We are independent art advisory firms serving private collectors." }], matches: [{ field: "organizationTypes", criterion: "art advisory firms", quote: "We are independent art advisory firms serving private collectors." }, { field: "geographies", criterion: "Europe", quote }, { field: "buyingSignals", criterion: "contemporary fine art", quote }] };
const company = normalizeProspect(candidate, page, plan)!;
const business = { name: "Studio Example", description: "An art studio", offer: "original contemporary paintings", valueProposition: "Works prepared for residential collections.", geography: null, website: null, evidence: [], status: "user_provided" as const };
function response(data: unknown, urls: string[] = []): IntelligenceResponse {
  return { citations: urls.map((url) => ({ url })), computeSource: "free-cloud", content: [{ type: "text", text: JSON.stringify(data) }], finishReason: "stop", model: "test", providerId: "test", toolCalls: [], usage: { cost: { amount: null, currency: null, source: "unknown" }, inputTokens: null, outputTokens: null, totalTokens: null, latencyMs: 0, model: "test", providerId: "test" } };
}
function fake(responses: IntelligenceResponse[]) {
  const requests: IntelligenceRequest[] = [];
  const deps: GrowthDiscoveryDependencies = { infer: async (request) => { requests.push(request); const next = responses.shift(); assert.ok(next, "unexpected model call"); return next; }, retrieve: async () => page };
  return { deps, requests };
}
const stubProvider: ProspectDiscoveryProvider = { id: "test", discoverCompanies: async () => ({ companies: [company], people: [], discovery: { status: "partial", checked: 1, rejected: 0, message: "One verified source", searchedAt: page.retrievedAt } }) };

test("explicit titles distinct from adjacent suggestions", () => { assert.deepEqual(plan.titles, ["Art Advisor", "Art Consultant", "Art Acquisition Director"]); assert.deepEqual(plan.adjacentTitles, ["Collection Manager"]); });
test("excluded titles cannot leak back", () => assert.deepEqual(normalizeSearchPlan({ titles: ["Designer"], excludedTitles: ["Designer"] }).titles, []));
test("geography seniority organization and buyer criteria preserved", () => { assert.deepEqual(plan.geographies, ["United States", "Europe"]); assert.deepEqual(plan.seniority, ["manager+"]); assert.equal(plan.organizationTypes.length, 2); assert.match(plan.companyCriteria, /high-net-worth/); });
test("state mutation composes independent additions and exclusions", () => {
  const next = mutateSearchPlan(plan, [{ field: "geographies", op: "add", values: ["Germany", "Netherlands"] }, { field: "excludedTitles", op: "add", values: ["Creative Director"] }, { field: "organizationTypes", op: "add", values: ["dedicated art advisory firms"] }]);
  assert.equal(next.geographies.length, 4); assert.equal(next.excludedTitles.length, 2); assert.equal(next.organizationTypes.length, 3); assert.equal(plan.geographies.length, 2);
});
test("only organization filter replaces list", () => assert.deepEqual(mutateSearchPlan(plan, [{ field: "organizationTypes", op: "set", values: ["hospitality groups"] }]).organizationTypes, ["hospitality groups"]));
test("top-N bounded", () => assert.equal(mutateSearchPlan(plan, [{ field: "limit", op: "set", value: 50000 }]).limit, 50));
test("unknown mutation fields fail closed", () => assert.throws(() => mutateSearchPlan(plan, [{ field: "ownerId", op: "set", value: "attacker" }])));
test("invalid mutation operation fails", () => assert.throws(() => mutateSearchPlan(plan, [{ field: "titles", op: "execute", values: [] }])));
test("generic non-art organization mutation", () => assert.deepEqual(mutateSearchPlan(normalizeSearchPlan({ organizationTypes: ["dental clinics"] }), [{ field: "organizationTypes", op: "add", values: ["veterinary clinics"] }]).organizationTypes, ["dental clinics", "veterinary clinics"]));
test("audience hypotheses retain buyer economics and signals", () => { const a = normalizeAudiences([{ name: "Clinics", problem: "Slow scheduling", whyTheyBuy: "Reduce empty appointment slots", buyerRoles: ["Practice manager"], organizationTypes: ["Clinics"], buyingSignals: ["Hiring receptionists"] }]); assert.equal(a[0].status, "inferred"); assert.equal(a[0].buyingSignals[0], "Hiring receptionists"); });
test("incomplete audiences are rejected", () => assert.equal(normalizeAudiences([{ name: "Everyone" }]).length, 0));
test("real source quote required", () => assert.equal(groundedEvidence([{ field: "claim", quote: "Invented quote that never appeared" }], page).length, 0));
test("company must appear in original source", () => assert.equal(normalizeProspect({ ...candidate, name: "Invented Company" }, page, plan), null));
test("directory is not a company", () => assert.equal(normalizeProspect({ ...candidate, isCompany: false }, page, plan), null));
test("explicit excluded candidate rejected", () => assert.equal(normalizeProspect({ ...candidate, excluded: true }, page, plan), null));
test("unknown fit criterion cannot become verified fit", () => assert.equal(normalizeProspect({ ...candidate, matches: [{ field: "buyingSignals", criterion: "billion dollar budget", quote }] }, page, plan), null));
test("unsupported location is unknown", () => assert.equal(normalizeProspect({ ...candidate, location: "New York" }, page, plan)?.location, null));
test("untrusted provider contact fields never copied", () => { const c = normalizeProspect({ ...candidate, email: "invented@example.com", phone: "000", person: "Made Up" }, page, plan); assert.doesNotMatch(JSON.stringify(c), /invented@example|Made Up|"phone"/); });
test("fit deterministic and associated with evidence", () => { assert.equal(company.fitScore, 75); assert.equal(company.fitReasons.length, 3); assert.ok(company.evidence.every((e) => e.url === page.url && e.checkedAt === page.retrievedAt)); });
test("outreach uses company-specific quotation and actual offer", () => { const draft = draftOutreach(company, business); assert.ok(draft.body.includes(quote)); assert.ok(draft.body.includes(business.offer)); assert.equal(draft.personalizationEvidence.length, 1); assert.doesNotMatch(draft.body, /first_name|sent successfully/); });
test("outreach without business offer fails", () => assert.throws(() => draftOutreach(company, null)));
test("CSV selected pool exact and unknown contact fields empty", () => { const state = { ...emptyGrowthDiscovery(), companies: [company, { ...company, id: "other", name: "Other" }] }; const csv = growthProspectsCsv(state, [company.id]); assert.ok(csv.includes(company.name)); assert.ok(!csv.includes('"Other"')); assert.match(csv, /"unknown"/); assert.equal(csv.split("\r\n").length, 3); });
test("CSV formula injection neutralized and quotes escaped", () => { const csv = growthProspectsCsv({ ...emptyGrowthDiscovery(), companies: [{ ...company, name: '=HYPERLINK("x")' }] }); assert.ok(csv.includes(`"'=HYPERLINK(""x"")"`)); });
test("verified-contact-only yields no invented results or provider calls", async () => { const f = fake([]); const result = await publicWebDiscovery.discoverCompanies({ ...plan, verifiedContactsOnly: true }, f.deps); assert.equal(result.companies.length, 0); assert.equal(f.requests.length, 0); assert.match(result.discovery.message, /No contact-verification/); });
test("live company path requires research citations and original-page evidence", async () => { const f = fake([response({ companies: [{ url: page.url }] }, [page.url]), response(candidate)]); const result = await publicWebDiscovery.discoverCompanies(plan, f.deps); assert.equal(result.companies.length, 1); assert.equal(f.requests[0].features?.webResearch?.maxResults, 5); assert.equal(f.requests[1].mode, "GROWTH"); });
test("uncited model URL not fetched", async () => { const f = fake([response({ companies: [{ url: "https://uncited.test" }] }, [page.url])]); f.deps.retrieve = async () => { throw new Error("must not fetch"); }; const result = await publicWebDiscovery.discoverCompanies(plan, f.deps); assert.equal(result.discovery.checked, 0); });
test("no-source research cannot claim success", async () => { const f = fake([response({ companies: [{ url: page.url }] })]); await assert.rejects(() => publicWebDiscovery.discoverCompanies(plan, f.deps), /no source references/); });
test("unreadable original page never becomes prospect", async () => { const f = fake([response({ companies: [{ url: page.url }] }, [page.url])]); f.deps.retrieve = async () => { throw new Error("network"); }; assert.equal((await publicWebDiscovery.discoverCompanies(plan, f.deps)).companies.length, 0); });
test("new search production service carries normalized plan to discovery", async () => { const f = fake([response({ plan })]); let observed: GrowthSearchPlan | null = null; const provider = { ...stubProvider, discoverCompanies: async (p: GrowthSearchPlan) => { observed = p; return stubProvider.discoverCompanies(p, f.deps); } }; const result = await runGrowthDiscovery({ previous: emptyGrowthDiscovery(), truth: null, action: "search", prompt: "Find senior art buyers" }, f.deps, provider); assert.deepEqual(observed, plan); assert.equal(result.companies.length, 1); assert.notEqual(result.revision, ""); });
test("refinement recalculates results from new search state", async () => { const f = fake([response({ operations: [{ field: "geographies", op: "add", values: ["Germany", "Netherlands"] }] })]); const previous = { ...emptyGrowthDiscovery(), plan, companies: [company] }; let called = false; const provider = { ...stubProvider, discoverCompanies: async (p: GrowthSearchPlan) => { called = true; assert.ok(p.geographies.includes("Netherlands")); return { ...(await stubProvider.discoverCompanies(p, f.deps)), companies: [] }; } }; const result = await runGrowthDiscovery({ previous, truth: null, action: "refine", prompt: "Add Germany and Netherlands" }, f.deps, provider); assert.ok(called); assert.equal(result.companies.length, 0); assert.equal(previous.companies.length, 1); });
test("discovery failure preserves structured criteria without stale results", async () => { const f = fake([response({ plan })]); const broken = { ...stubProvider, discoverCompanies: async () => { throw new Error("unavailable"); } }; const result = await runGrowthDiscovery({ previous: emptyGrowthDiscovery(), truth: null, action: "search", prompt: "Find companies" }, f.deps, broken); assert.deepEqual(result.plan, plan); assert.equal(result.discovery.status, "unavailable"); assert.equal(result.companies.length, 0); });
test("cancelled action cannot return updated state", async () => { const controller = new AbortController(); controller.abort(); await assert.rejects(() => runGrowthDiscovery({ previous: emptyGrowthDiscovery(), truth: null, action: "search", prompt: "Find companies", signal: controller.signal }, fake([]).deps), /cancelled/); });
test("business URL analysis stages grounded facts before audiences", async () => { const f = fake([
  response({ business: { name: "Example Advisory", offer: "art sourcing", description: quote, evidence: [{ field: "offer", quote }] } }),
  response({ audiences: [{ name: "Collectors", problem: "Acquisition support", whyTheyBuy: "Independent expertise", buyerRoles: ["Collector"] }] })
]); const result = await runGrowthDiscovery({ previous: emptyGrowthDiscovery(), truth: null, action: "analyze", prompt: page.url }, f.deps); assert.equal(result.business?.website, page.url); assert.equal(result.business?.evidence[0].quote, quote); assert.equal(result.audiences.length, 1); assert.equal(f.requests.length, 2); assert.equal(f.requests[0].generation?.maxOutputTokens, 1_400); assert.equal(f.requests[1].generation?.maxOutputTokens, 1_800); });
test("outreach selection ignores IDs outside current project pool", async () => { const previous = { ...emptyGrowthDiscovery(), business, companies: [company] }; const result = await runGrowthDiscovery({ previous, truth: null, action: "outreach", prompt: "Draft", selectedIds: [company.id, "another-project-company"] }, fake([]).deps); assert.equal(result.drafts.length, 1); });

test("malformed persisted discovery cannot crash the UI", () => assert.deepEqual(readDiscoveryState({ ...emptyGrowthDiscovery(), companies: [{}] }), emptyGrowthDiscovery()));
test("valid persisted discovery round-trips", () => { const state = { ...emptyGrowthDiscovery(), business, plan, companies: [company] }; assert.deepEqual(readDiscoveryState(JSON.parse(JSON.stringify(state))), state); });
test("stored unsafe company URL rejected", () => assert.deepEqual(readDiscoveryState({ ...emptyGrowthDiscovery(), companies: [{ ...company, website: "javascript:alert(1)" }] }), emptyGrowthDiscovery()));
let passed = 0;
for (const [name, run] of cases) { await run(); passed++; console.log(`PASS ${name}`); }
console.log(`Growth discovery: ${passed}/${cases.length} PASS`);
