import assert from "node:assert/strict";
import { emptyGrowthDiscovery, type GrowthAudienceSegment } from "@/lib/growth-discovery";
import { applyExplicitSize, audiencePlanFields, companySizeResult, extractCompanySize, sizeRejection } from "../growth-audience-constraints";
import { normalizeProspect, normalizeSearchPlan, mutateSearchPlan, readDiscoveryState } from "../growth-discovery-core";
import { createDiscoveryJob, discoveryProfile } from "../growth-job-engine";
import { publicWebDiscovery, runGrowthDiscovery, type GrowthDiscoveryDependencies } from "../growth-discovery-service";
import type { IntelligenceResponse } from "@/lib/server/intelligence/intelligence-contract";

const audience: GrowthAudienceSegment = { id: "a", name: "Growing mid-size consultancies (50\u2013200 employees)", problem: "Fragmented communication", whyTheyBuy: "Coordinate projects", organizationTypes: ["Professional services"], geography: ["Europe"], exclusions: ["Recruitment businesses"], buyerRoles: ["PMO Lead"], buyingSignals: ["Remote coordination"], status: "inferred" };
const plan = normalizeSearchPlan(audiencePlanFields(audience));
const hard = applyExplicitSize(plan, "Find companies with 50-200 employees.");
const quote = "Example is an engineering consultancy based in Germany.";
const page = { url: "https://example.test/", title: "Example", content: `${quote} Our company has 120 employees.`, retrievedAt: "2026-09-08T00:00:00Z" };
const candidate = { isCompany: true, excluded: false, pageKind: "company", name: "Example", evidence: [{field:"offering",quote}], matches: [{field:"organizationTypes",criterion:"Professional services",quote},{field:"geographies",criterion:"Europe",quote}] };
const reply = (data:unknown):IntelligenceResponse => ({content:[{type:"text",text:JSON.stringify(data)}],citations:[],computeSource:"free-cloud",finishReason:"stop",model:"fixture",providerId:"fixture",toolCalls:[],usage:{inputTokens:null,outputTokens:null,totalTokens:null,latencyMs:0,cost:{amount:null,currency:null,source:"unknown"},model:"fixture",providerId:"fixture"}});
const deps: GrowthDiscoveryDependencies = {search:async()=>[page.url],retrieve:async()=>page,infer:async()=>reply(candidate)};
const tests: Array<[string,()=>unknown|Promise<unknown>]> = [];
const test=(name:string,run:()=>unknown|Promise<unknown>)=>tests.push([name,run]);
const proof=(quote:string)=>[{url:page.url,quote,field:"companySize",checkedAt:page.retrievedAt}];

test("all actual audience fields survive without sibling overwrites",()=>{ assert.deepEqual(plan.audienceContext,audience); assert.equal(plan.companyCriteria,audience.problem); assert.equal(plan.reasoning,audience.whyTheyBuy); assert.deepEqual(plan.organizationTypes,audience.organizationTypes); assert.deepEqual(plan.geographies,audience.geography); assert.deepEqual(plan.exclusions,audience.exclusions); assert.deepEqual(plan.titles,audience.buyerRoles); assert.deepEqual(plan.buyingSignals,audience.buyingSignals); });
test("range embedded in label remains numeric and inferred",()=>{ assert.equal(plan.companySize?.value?.minEmployees,50); assert.equal(plan.companySize?.value?.maxEmployees,200); assert.equal(plan.companySize?.status,"inferred"); });
test("explicit user employee range is confirmed",()=>assert.equal(hard.companySize?.status,"confirmed"));
test("vague descriptions never acquire invented numeric thresholds",()=>{ for(const label of ["SMB","mid-size","enterprise","large enterprises"]) { const v=extractCompanySize(label)!; assert.equal(v.minEmployees,null); assert.equal(v.maxEmployees,null); } });
test("numeric range examples generalize",()=>{ for(const [min,max] of [[1,10],[11,50],[50,200],[201,500]]) assert.equal(extractCompanySize(`${min}\u2011${max} employees`)?.maxEmployees,max); });
test("unrelated refinement preserves confirmed authority and source",()=>assert.deepEqual(applyExplicitSize(mutateSearchPlan(hard,[{field:"limit",op:"set",value:3}]),"Keep the mid-size audience unchanged. Set maximum results to 3." ).companySize,hard.companySize));
test("typed request is explicit even when it resembles a selection label",()=>assert.equal(applyExplicitSize(plan,`Find customers: ${audience.name}`).companySize?.status,"confirmed"));
test("new explicit user size replaces older inferred range",()=>assert.equal(applyExplicitSize(plan,"Require companies with 201-500 employees").companySize?.value?.minEmployees,201));
test("exclusion text does not become positive size target",()=>assert.deepEqual(applyExplicitSize(plan,"Exclude companies with 1-10 employees").companySize,plan.companySize));
test("bounds survive normalization and persistence round trip",()=>{ const state={...emptyGrowthDiscovery(),audiences:[audience],plan:hard}; assert.deepEqual(readDiscoveryState(JSON.parse(JSON.stringify(state))).plan,hard); });
test("audience snapshot is independent of future caller mutation",()=>{ const copy=structuredClone(audience); const mapped=audiencePlanFields(copy); copy.buyerRoles.push("Mutated"); assert.deepEqual(mapped.audienceContext?.buyerRoles,audience.buyerRoles); });
test("profile and job retain audience and size without query role contamination",async()=>{ const p=await discoveryProfile(hard,{...deps,infer:async()=>reply({categories:[]})}); assert.deepEqual(p.companySize,hard.companySize); assert.deepEqual(p.audienceContext,audience); const job=createDiscoveryJob(hard,p); assert.deepEqual(job.profile.companySize,hard.companySize); assert.ok(job.queries.every(q=>!q.text.includes("PMO"))); assert.ok(job.queries.some(q=>!q.text.includes("50-200"))); });
test("hard exact observed size passes",()=>assert.equal(sizeRejection(companySizeResult(hard,proof("Our company has 120 employees."))),null));
test("wrong hard size is typed rejection",()=>assert.equal(sizeRejection(companySizeResult(hard,proof("Our company has 500 employees."))),"GROWTH_DISCOVERY_WRONG_COMPANY_SIZE"));
test("unknown hard size fails closed",()=>assert.equal(sizeRejection(companySizeResult(hard,[])),"GROWTH_DISCOVERY_SIZE_UNVERIFIED"));
test("overlapping range does not prove compliance",()=>assert.equal(sizeRejection(companySizeResult(hard,proof("Our company has 51-500 employees."))),"GROWTH_DISCOVERY_SIZE_UNVERIFIED"));
test("conflicting counts remain unknown",()=>assert.equal(companySizeResult(hard,[...proof("We have 120 employees."),...proof("We have 500 employees.")])?.match,"unverified"));
test("inferred size does not silently become hard exclusion",()=>assert.equal(sizeRejection(companySizeResult(plan,[])),null));
test("buyer-role proof never substitutes for company-size evidence",()=>assert.equal(companySizeResult(hard,[{...proof("We have 120 employees.")[0],field:"titles"}])?.match,"unverified"));
test("secondary size source cannot replace official company identity",()=>assert.equal(normalizeProspect({...candidate,evidence:[...candidate.evidence,...proof("Our company has 120 employees.")]},{...page,url:"https://linkedin.com/company/example"},hard),null));
test("production verifier fails hard size without a provider retry",async()=>{let calls=0;const result=await publicWebDiscovery.discoverCompanies(hard,{...deps,infer:async()=>{calls++;return reply(candidate);}});assert.equal(calls,1);assert.equal(result.companies.length,0);assert.equal(result.discovery.funnel?.rejections.GROWTH_DISCOVERY_SIZE_UNVERIFIED,1);});
test("production verifier accepts grounded hard size without buyer-role evidence",async()=>{const result=await publicWebDiscovery.discoverCompanies(hard,{...deps,infer:async()=>reply({...candidate,evidence:[...candidate.evidence,{field:"companySize",quote:"Our company has 120 employees."}]})});assert.equal(result.companies.length,1);assert.equal(result.companies[0].companySize?.match,"match");});
test("audience selection service passes full criteria to company verifier",async()=>{const previous={...emptyGrowthDiscovery(),audiences:[audience]};let observed=false;await runGrowthDiscovery({previous,truth:null,action:"audience",audienceId:"a",prompt:`Find customers: ${audience.name}`},deps,{id:"test",discoverCompanies:async(p)=>{assert.deepEqual(p.audienceContext,audience);assert.equal(p.companySize?.status,"inferred");observed=true;return {companies:[],people:[],discovery:previous.discovery};}});assert.ok(observed);});
let passed=0;
test("open-ended evidence does not become an exact employee count",()=>assert.equal(companySizeResult(hard,proof("Our company has over 120 employees."))?.match,"unverified"));
test("explicit lower bound retains its open upper bound",()=>{const p=applyExplicitSize(plan,"Find companies with at least 50 employees.");assert.equal(p.companySize?.value?.minEmployees,50);assert.equal(p.companySize?.value?.maxEmployees,null);assert.equal(sizeRejection(companySizeResult(p,proof("We have 120 employees."))),null);});
test("approximate counts do not satisfy an exact hard range",()=>assert.equal(companySizeResult(hard,proof("Our company has about 120 employees."))?.match,"unverified"));
test("malformed stored size cannot silently erase a required constraint",()=>{const state={...emptyGrowthDiscovery(),plan:{...hard,companySize:{...hard.companySize,value:{label:"bad",minEmployees:-1,maxEmployees:200}}}};assert.equal(readDiscoveryState(state).plan,null);});
for(const [name,run] of tests){await run();passed++;console.log(`PASS ${name}`);}
console.log(`Growth audience constraints: ${passed}/${tests.length} PASS`);
