import assert from "node:assert/strict";
import { emptyGrowthDiscovery, emptyGrowthFunnel, growthProspectsCsv, type GrowthDiscoveryState, type GrowthProspectCompany } from "@/lib/growth-discovery";
import { validGrowthJob } from "@/lib/growth-discovery-job";
import { claimDiscoveryWork, controlDiscoveryJob, createDiscoveryJob, executeDiscoveryWork } from "../growth-job-engine";
import { processGrowthJob } from "../growth-job-request";
import { enforceOrganizationAuthority, normalizeSearchPlan, readDiscoveryState, validSearchPlanShape } from "../growth-discovery-core";
import type { GrowthDiscoveryDependencies, ProspectDiscoveryProvider } from "../growth-discovery-service";
import { outreachSimilarity, personalizationBrief } from "../growth-personalization";

const cases: Array<[string, () => unknown | Promise<unknown>]> = [];
const test = (name: string, run: () => unknown | Promise<unknown>) => cases.push([name, run]);
const plan = normalizeSearchPlan({ organizationTypes: ["consultancies"], geographies: ["UK"], limit: 500 });
const profile = { categories: Array.from({ length: 24 }, (_, i) => ({ term: `specialty ${i} consultancy`, parent: "consultancies" })), geographies: ["UK", "London", "Manchester"], fitSignals: ["potential offer fit"] };
const initial = (): GrowthDiscoveryState => ({ ...emptyGrowthDiscovery(), plan, job: createDiscoveryJob(plan, profile, 1000) });
const company = (url: string): GrowthProspectCompany => ({ id: new URL(url).hostname, name: new URL(url).hostname, website: url, domain: new URL(url).hostname, location: "UK", organizationType: "consultancy", segment: "consultancies", fitScore: 60, fitReasons: ["Original-page fixture evidence"], evidence: [{ url, quote: "Our consultancy supports UK organizations.", field: "organizationTypes", checkedAt: "2026-09-06" }], lastVerifiedAt: "2026-09-06", targetRoles: [], recommendedAngle: "Consulting fit" });
const deps: GrowthDiscoveryDependencies = { infer: async () => { throw new Error("Unexpected inference"); }, retrieve: async () => { throw new Error("Unexpected retrieval"); }, searchQuery: async () => [] };
const verifier: ProspectDiscoveryProvider = { id: "fixture-original-evidence", discoverCompanies: async (p, d, signal) => { const urls = await d.search!(p, signal); return { companies: urls.map(company), people: [], discovery: { status: "partial", checked: urls.length, rejected: 0, message: "fixture", searchedAt: null, funnel: { ...emptyGrowthFunnel(p.limit), fetched: urls.length, recognized: urls.length, audienceMatches: urls.length, evidenceValid: urls.length } } }; } };

test("500 target and query portfolio reserve bounded seed capacity", () => { const state = initial(); assert.equal(state.job!.target, 500); assert.equal(state.job!.queries.length, 114); assert.equal(new Set(state.job!.queries.map(q => q.round)).size, 3); assert.deepEqual(readDiscoveryState(JSON.parse(JSON.stringify(state))), state); });
test("company categories cannot masquerade as human buyer roles", () => assert.equal(validSearchPlanShape({ titles: ["Video studios"], organizationTypes: ["Video studios"] }), false));
test("explicit grounded company set overrides generated broadening", () => { const request = "Find only architecture firms and interior design studios in Canada."; const result = enforceOrganizationAuthority(normalizeSearchPlan({ organizationTypes: ["creative agencies", "architecture firms"] }), { exclusive: true, quote: request, values: ["architecture firms", "interior design studios"] }, request); assert.deepEqual(result.organizationTypes, ["architecture firms", "interior design studios"]); });
test("invented exclusive authority is rejected", () => assert.throws(() => enforceOrganizationAuthority(plan, { exclusive: true, quote: "only retailers", values: ["retailers"] }, "Find consultancies"), /UNGROUNDED/));
test("nonexclusive scope keeps the proposed plan", () => assert.deepEqual(enforceOrganizationAuthority(plan, { exclusive: false }, "Find consultancies"), plan));
test("directory seeds consume the existing query budget and remain unverified", async () => { const state = initial(); state.job!.candidates = [{ url: "https://directory.test/", attempts: 0 }]; const result = await executeDiscoveryWork(claimDiscoveryWork(state), deps, { ...verifier, discoverCompanies: async () => ({ companies: [], people: [], discovery: { status: "unavailable", checked: 1, rejected: 1, searchedAt: null, message: "directory", seedQueries: ["Observed Company official website"] } }) }); assert.equal(result.companies.length, 0); assert.equal(result.job!.queries[0].text, "Observed Company official website"); assert.ok(result.job!.queries.length <= result.job!.limits.queries); });
test("malformed nested job fails closed without throwing", () => { for (const patch of [{ profile: { categories: [null] } }, { funnel: {} }, { queries: [null] }, { lease: {} }]) assert.equal(validGrowthJob({ ...initial().job, ...patch }), false); });
test("search claim increments budget before external work", () => { const state = claimDiscoveryWork(initial(), 1001); assert.equal(state.job!.funnel.queries, 1); assert.equal(state.job!.lease!.work.kind, "search"); });
test("unexpired lease excludes second worker", () => assert.throws(() => claimDiscoveryWork(claimDiscoveryWork(initial(), 1001), 1002), /Another session/));
test("expired lease pauses instead of uncontrolled retry", () => { const state = claimDiscoveryWork(claimDiscoveryWork(initial(), 1001), 200000); assert.equal(state.job!.status, "paused"); assert.equal(state.job!.lease, null); });
test("cancelled job never claims more work", () => { const state = controlDiscoveryJob(initial(), "cancel"); assert.equal(claimDiscoveryWork(state).job!.lease, null); assert.throws(() => controlDiscoveryJob(state, "resume"), /finished/); });
test("active time ceiling terminates job", () => { const state = initial(); state.job!.activeMs = state.job!.limits.activeMs; assert.equal(claimDiscoveryWork(state).job!.status, "exhausted"); });
test("page budget is reserved before calls including root recovery", () => { const state = initial(); state.job!.candidates = [{ url: "https://fixture.test/article", attempts: 0 }]; state.job!.limits.pageFetches = 2; const claimed = claimDiscoveryWork(state); assert.equal(claimed.job!.pageRequests, 2); assert.equal(claimed.job!.lease?.work.kind, "verify"); const saved = { ...claimed, job: { ...claimed.job!, lease: null } }; assert.equal(claimDiscoveryWork(saved).job!.status, "exhausted"); });
test("search failure pauses and records reason counts", async () => { const result = await executeDiscoveryWork(claimDiscoveryWork(initial()), { ...deps, searchQuery: async () => { throw new Error("fixture unavailable"); } }, verifier); assert.equal(result.job!.status, "paused"); assert.equal(result.job!.funnel.rejections.GROWTH_BATCH_FAILED, 1); assert.equal(result.companies.length, 0); });
test("partial verification saves success and retries only the failed neighbor", async () => { const state = initial(); state.job!.candidates = [{ url: "https://good.test/", attempts: 0 }, { url: "https://failed.test/", attempts: 0 }]; const result = await executeDiscoveryWork(claimDiscoveryWork(state), deps, { ...verifier, discoverCompanies: async () => ({ companies: [company("https://good.test/")], people: [], discovery: { status: "partial", checked: 2, rejected: 1, searchedAt: null, message: "partial", failureCode: "GROWTH_RATE_LIMIT", retryUrls: ["https://failed.test/"] } }) }); assert.equal(result.companies.length, 1); assert.equal(result.job!.status, "paused"); assert.equal(result.job!.candidates.length, 3); assert.equal(result.job!.candidates[2].url, "https://failed.test/"); });
test("URL credentials rejected and www domains deduplicated", async () => { const result = await executeDiscoveryWork(claimDiscoveryWork(initial()), { ...deps, searchQuery: async () => ["https://www.example.test/about", "https://example.test/", "https://user:pass@other.test/", "javascript:alert(1)"] }, verifier); assert.equal(result.job!.candidates.length, 1); assert.equal(result.job!.funnel.duplicateDomains, 1); assert.equal(result.job!.funnel.preRetrievalRejected, 2); });
test("query exhaustion is not fake target completion", async () => { const state = initial(); state.job!.queryIndex = state.job!.queries.length; assert.equal(claimDiscoveryWork(state).job!.status, "exhausted"); });
test("failed CAS runs no external work", async () => { let calls = 0; const state = initial(); await assert.rejects(() => processGrowthJob({ previous: state, action: "advance", jobId: state.job!.id, revision: state.revision, save: async () => false }, { ...deps, searchQuery: async () => { calls++; return []; } }, verifier), /before the batch/); assert.equal(calls, 0); });
test("superseded final CAS cannot apply batch", async () => { let writes = 0; const state = initial(); await assert.rejects(() => processGrowthJob({ previous: state, action: "advance", jobId: state.job!.id, revision: state.revision, save: async () => ++writes === 1 }, deps, verifier), /not applied/); assert.equal(writes, 2); });
test("foreign job identity rejected before persistence", async () => { const state = initial(); await assert.rejects(() => processGrowthJob({ previous: state, action: "advance", jobId: "other-project-job", revision: state.revision, save: async () => { throw new Error("must not save"); } }, deps, verifier), /job has changed/); });
test("original plan retained for every verification batch", async () => { const state = initial(); state.job!.candidates = [{ url: "https://fixture.test/", attempts: 0 }]; await executeDiscoveryWork(claimDiscoveryWork(state), deps, { ...verifier, discoverCompanies: async (p, d) => { assert.deepEqual(p, plan); return verifier.discoverCompanies(p, d); } }); });
test("deep-link failure retries canonical homepage, not a fabricated prospect", async () => { const state = initial(); state.job!.candidates = [{ url: "https://fixture.test/article", attempts: 0 }]; let calls = 0; const result = await executeDiscoveryWork(claimDiscoveryWork(state), deps, { ...verifier, discoverCompanies: async (p, d) => { calls++; const urls = await d.search!(p); return urls[0].endsWith("/article") ? { companies: [], people: [], discovery: { status: "unavailable", checked: 1, rejected: 1, searchedAt: null, message: "unreadable" } } : verifier.discoverCompanies(p, d); } }); assert.equal(calls, 2); assert.equal(result.companies[0].website, "https://fixture.test/"); });
test("name/quote-swapped templates are detected", () => { const a = { companyId: "a", subject: "Offer for Alpha", body: "Hello Alpha, I noticed Alpha does excellent work. Would a short call be worthwhile to explore our offering?", recommendedAngle: "fit", personalizationEvidence: [], status: "draft" as const }; assert.ok(outreachSimilarity(a, { ...a, companyId: "b", subject: "Offer for Beta", body: a.body.replaceAll("Alpha", "Beta") }, ["Alpha", "Beta"]) > 0.9); });
test("brief includes observed evidence, not invented contacts", () => { const b = personalizationBrief(company("https://example.test"), { name: "Seller", description: "", offer: "Advice", valueProposition: "", geography: null, website: null, evidence: [], status: "user_provided" }); assert.equal(b.evidence.length, 1); assert.ok(!("email" in b.company)); });
test("500-company fixture job finishes with bounded two-company batches and resumable checkpoints", async () => {
  let state = initial(), searched = 0, batches = 0;
  const live = { ...deps, searchQuery: async () => Array.from({ length: 20 }, (_, i) => `https://fixture-${searched * 20 + i}.test/`) };
  for (let step = 0; step < 400; step++) {
    state = claimDiscoveryWork(readDiscoveryState(JSON.parse(JSON.stringify(state))));
    if (!state.job!.lease) break;
    if (state.job!.lease.work.kind === "search") searched++;
    else { assert.ok(state.job!.lease.work.candidates.length <= 2); batches++; }
    state = await executeDiscoveryWork(state, live, verifier);
    if (state.job!.status === "complete") break;
  }
  assert.equal(state.companies.length, 500); assert.equal(state.job!.status, "complete"); assert.equal(searched, 25); assert.equal(batches, 250);
  assert.equal(readDiscoveryState(state).companies.length, 500);
  assert.equal(growthProspectsCsv(state).split("\r\n").length, 502);
});
const info = console.info; console.info = () => {};
try { for (const [name, run] of cases) { await run(); console.log(`PASS ${name}`); } } finally { console.info = info; }
console.log(`Growth commercial jobs: ${cases.length}/${cases.length} PASS (fixtures, not live discovery)`);
