import { getConfiguredProviderInfo, resolveAskProvider } from "@/lib/server/ai/provider-router";
import { findHassaliModel } from "@/lib/model-registry";

function isIdentityQuestion(prompt: string) {
  return /^(?:hi[, ]+)?(?:who are you|what are you|who designed you|who built you|what is your version|how are you running|how can i improve your intelligence)[?.! ]*$/i.test(prompt.trim());
}

function isProviderQuestion(prompt: string) {
  return /\b(?:what model|which model|current model|model are you using|provider|advanced models|what ai model)\b/i.test(prompt);
}

export function createHassaliIdentityAnswer(input: {
  model?: string | null;
  prompt: string;
}) {
  const provider = getConfiguredProviderInfo({
    requestedModel: input.model
  });
  const resolvedProvider = resolveAskProvider(input.model ?? "");

  if (isProviderQuestion(input.prompt)) {
    const model = findHassaliModel(input.model);
    const displayName = model?.displayName ?? resolvedProvider.resolvedModelId ?? "the selected model";
    const providerName = resolvedProvider.executionProvider === "openrouter" ? "OpenRouter" : resolvedProvider.executionProvider;
    const wantsTechnicalDiagnostics = /\b(?:technical|diagnostic|configuration|configured|registry|endpoint|server status|provider status)\b/i.test(input.prompt);

    if (!wantsTechnicalDiagnostics) {
      return `The selected ASK model is ${displayName}${providerName ? ` through ${providerName}` : ""}. This status reply itself is generated by Hassali's local system handler.`;
    }

    return [
      `Selected model: ${displayName}`,
      `Resolved model: ${resolvedProvider.resolvedModelId ?? "unavailable"}`,
      `Execution provider: ${providerName ?? "unavailable"}`,
      `Configured: ${resolvedProvider.configured ? "yes" : "no"}`,
      `Local model endpoints configured: ${provider.localModelsConfigured ? "yes" : "no"}`,
      "No credential values are exposed in this status response."
    ].join("\n");
  }

  if (!isIdentityQuestion(input.prompt)) {
    return null;
  }

  if (/\bhow can i improve your intelligence\b/i.test(input.prompt)) {
    return [
      "You can improve Hassali's practical intelligence by giving it clearer project context, exact mode intent, current files, desired pages/features, constraints, and examples of what to avoid.",
      "",
      "Hassali itself improves through its orchestration stack: intent translation, project contracts, validators, repair checks, preview/runtime awareness, and configurable provider routing. The safest way to get better output is to state the target domain, exact files/pages, quality bar, and approval constraints."
    ].join("\n");
  }

  return [
    "I am Hassali.ai, a calm AI software creation workspace.",
    "",
    "In ASK mode, I help you think, write, plan, explain, debug, compare options, and write code as text without changing files. WEBSITE and CODE are the executor modes: they can create approval-first proposals when you want Hassali to build or modify actual project files."
  ].join("\n");
}
