export type WebsiteBusinessModel =
  | "consulting"
  | "custom_build"
  | "education"
  | "healthcare"
  | "hospitality"
  | "installation"
  | "manufacturing"
  | "marketplace"
  | "professional_practice"
  | "rental"
  | "repair"
  | "retail"
  | "saas"
  | "service"
  | "subscription"
  | "wholesale";

export type UniversalIndustryNode = {
  aliases: string[];
  audienceSignals: string[];
  businessModels: WebsiteBusinessModel[];
  capabilities: string[];
  category: string;
  displayName: string;
  id: string;
  parentIds: string[];
  productSignals: string[];
  relatedTerms: string[];
  sector: string;
  serviceSignals: string[];
  trustSignals: string[];
  visualSignals: string[];
};

function node(input: UniversalIndustryNode): UniversalIndustryNode {
  return input;
}

/**
 * Broad grounding for semantic resolution. This catalog is intentionally not a
 * closed list of businesses: niches and sub-niches are composed at request time.
 */
export const WEBSITE_INDUSTRY_CATALOG: UniversalIndustryNode[] = [
  node({ id: "accounting_finance", displayName: "Accounting and Financial Services", sector: "Financial and Professional Services", category: "Accounting, Tax, and Finance", parentIds: ["professional_services", "financial_services"], aliases: ["accounting", "accountant", "bookkeeping", "tax advisory", "finance firm"], relatedTerms: ["audit", "payroll", "compliance", "financial reporting", "invoices"], productSignals: ["financial reports", "tax records", "management accounts"], serviceSignals: ["bookkeeping", "tax preparation", "payroll", "audit support", "financial planning"], audienceSignals: ["freelancers", "small businesses", "finance teams", "founders"], businessModels: ["professional_practice", "consulting", "service", "saas"], capabilities: ["accounting", "finance", "compliance", "records", "reporting", "professional_service"], trustSignals: ["clear scope", "confidential handling", "qualified review", "documented records"], visualSignals: ["ledger structure", "financial flow", "calm data hierarchy"] }),
  node({ id: "advertising_marketing", displayName: "Advertising and Marketing", sector: "Business Services", category: "Marketing, Communications, and Growth", parentIds: ["professional_services", "media"], aliases: ["advertising", "marketing agency", "marketing strategist", "branding agency", "public relations"], relatedTerms: ["campaign", "positioning", "conversion", "audience", "media buying"], productSignals: ["campaign concepts", "brand systems", "content plans"], serviceSignals: ["strategy", "creative direction", "campaign management", "content marketing", "public relations"], audienceSignals: ["brands", "founders", "marketing teams", "local businesses"], businessModels: ["consulting", "service"], capabilities: ["marketing", "positioning", "campaigns", "creative", "growth"], trustSignals: ["clear deliverables", "channel fit", "measured outcomes"], visualSignals: ["campaign layers", "message systems", "editorial composition"] }),
  node({ id: "agriculture_food_systems", displayName: "Agriculture and Food Systems", sector: "Agriculture and Natural Resources", category: "Farming, Agritech, and Agricultural Equipment", parentIds: ["agriculture", "industrial"], aliases: ["agriculture", "farm", "farming", "agritech", "hydroponic", "greenhouse", "aquaculture"], relatedTerms: ["irrigation", "crops", "soil", "controlled environment", "harvest"], productSignals: ["growing systems", "farm equipment", "sensors", "irrigation equipment", "produce"], serviceSignals: ["farm management", "installation", "crop support", "monitoring"], audienceSignals: ["growers", "farm operators", "food producers", "agricultural businesses"], businessModels: ["manufacturing", "service", "installation", "wholesale"], capabilities: ["agriculture", "equipment", "controlled_environment", "sustainability", "operations"], trustSignals: ["field suitability", "service coverage", "operating guidance"], visualSignals: ["growing rows", "water channels", "field systems", "sensor networks"] }),
  node({ id: "aviation_drones", displayName: "Aviation and Drone Services", sector: "Transportation and Aerospace", category: "Aircraft, Drones, and Aerial Services", parentIds: ["transportation", "engineering"], aliases: ["aviation", "airline", "aerospace", "drone", "unmanned aircraft", "uav"], relatedTerms: ["flight", "aerial", "pilot", "aircraft", "inspection"], productSignals: ["drones", "cameras", "flight controllers", "batteries", "payload systems"], serviceSignals: ["aerial inspection", "cinematography", "mapping", "flight operations", "maintenance"], audienceSignals: ["operators", "filmmakers", "survey teams", "industrial clients"], businessModels: ["retail", "service", "manufacturing", "rental"], capabilities: ["aviation", "drone", "imaging", "inspection", "technical_product"], trustSignals: ["operating boundaries", "trained operators", "equipment support"], visualSignals: ["airframe geometry", "flight paths", "camera gimbals", "aerial perspective"] }),
  node({ id: "architecture_design", displayName: "Architecture and Spatial Design", sector: "Built Environment", category: "Architecture, Interiors, and Spatial Design", parentIds: ["design", "construction"], aliases: ["architecture", "architect", "interior design", "interior designer", "spatial design", "landscape architecture"], relatedTerms: ["building", "space planning", "materials", "massing", "floor plan"], productSignals: ["design concepts", "plans", "material palettes", "project studies"], serviceSignals: ["architecture", "interior design", "space planning", "project consultation"], audienceSignals: ["homeowners", "developers", "commercial clients", "institutions"], businessModels: ["professional_practice", "consulting", "service"], capabilities: ["architecture", "spatial", "materials", "planning", "design"], trustSignals: ["project process", "scope clarity", "technical coordination"], visualSignals: ["building volumes", "floor plates", "material planes", "spatial sequence"] }),
  node({ id: "automotive_mobility", displayName: "Automotive and Mobility", sector: "Transportation and Mobility", category: "Vehicles, Mobility Products, and Vehicle Services", parentIds: ["transportation", "manufacturing"], aliases: ["automotive", "vehicle", "car", "motorcycle", "electric motorcycle", "mobility"], relatedTerms: ["engine", "ev", "fleet", "performance", "transport"], productSignals: ["vehicles", "parts", "accessories", "charging equipment"], serviceSignals: ["vehicle sales", "repair", "maintenance", "rental", "fleet support"], audienceSignals: ["drivers", "riders", "fleet operators", "vehicle buyers"], businessModels: ["retail", "manufacturing", "repair", "rental", "service"], capabilities: ["automotive", "mobility", "technical_product", "performance", "service"], trustSignals: ["service support", "clear specifications", "safety guidance"], visualSignals: ["body surfaces", "component layers", "road motion", "mechanical detail"] }),
  node({ id: "banking_fintech_insurance", displayName: "Banking, Fintech, and Insurance", sector: "Financial Services", category: "Banking, Payments, Lending, and Insurance", parentIds: ["financial_services", "software"], aliases: ["banking", "bank", "fintech", "insurance", "payments", "lending"], relatedTerms: ["transactions", "claims", "risk", "wallet", "credit"], productSignals: ["accounts", "payment tools", "insurance plans", "lending products"], serviceSignals: ["financial services", "claims support", "payment processing", "risk assessment"], audienceSignals: ["consumers", "businesses", "finance teams", "policyholders"], businessModels: ["service", "saas", "subscription"], capabilities: ["finance", "transactions", "risk", "security", "workflow"], trustSignals: ["security controls", "transparent terms", "regulated review"], visualSignals: ["transaction paths", "account layers", "risk signals"] }),
  node({ id: "biotech_pharmaceutical", displayName: "Biotechnology and Pharmaceuticals", sector: "Life Sciences", category: "Biotech, Pharmaceutical, and Laboratory Products", parentIds: ["healthcare", "research", "manufacturing"], aliases: ["biotechnology", "biotech", "pharmaceutical", "pharma", "synthetic biology", "life science"], relatedTerms: ["laboratory", "molecule", "research", "clinical", "diagnostic"], productSignals: ["research tools", "laboratory systems", "diagnostic products", "therapeutic platforms"], serviceSignals: ["research services", "laboratory analysis", "clinical support"], audienceSignals: ["researchers", "laboratories", "health organizations", "industry partners"], businessModels: ["manufacturing", "service", "saas"], capabilities: ["life_science", "research", "laboratory", "precision", "regulated_product"], trustSignals: ["evidence boundaries", "quality systems", "qualified review"], visualSignals: ["molecular structures", "laboratory layers", "cellular patterns"] }),
  node({ id: "blockchain_web3", displayName: "Blockchain and Digital Assets", sector: "Technology", category: "Blockchain, Web3, and Distributed Systems", parentIds: ["software", "financial_services"], aliases: ["blockchain", "web3", "crypto", "digital asset", "distributed ledger"], relatedTerms: ["smart contract", "token", "wallet", "decentralized", "protocol"], productSignals: ["protocols", "wallets", "smart-contract tools", "analytics"], serviceSignals: ["protocol development", "security review", "integration", "consulting"], audienceSignals: ["developers", "organizations", "digital-asset users"], businessModels: ["saas", "consulting", "service"], capabilities: ["blockchain", "distributed_systems", "security", "software"], trustSignals: ["security review", "transparent limitations", "protocol documentation"], visualSignals: ["distributed nodes", "ledger blocks", "network paths"] }),
  node({ id: "construction_property", displayName: "Construction and Property Development", sector: "Built Environment", category: "Construction, Contracting, and Development", parentIds: ["built_environment", "industrial"], aliases: ["construction", "contractor", "builder", "property development", "residential construction", "commercial construction"], relatedTerms: ["site", "project", "building", "contracting", "fit out"], productSignals: ["completed projects", "building systems", "construction materials"], serviceSignals: ["construction", "project delivery", "renovation", "fit-out", "site management"], audienceSignals: ["homeowners", "developers", "commercial clients"], businessModels: ["service", "professional_practice", "manufacturing"], capabilities: ["construction", "project_delivery", "built_environment", "materials"], trustSignals: ["project stages", "site safety", "scope clarity"], visualSignals: ["structural frames", "site grids", "building assemblies"] }),
  node({ id: "computer_hardware", displayName: "Computers and Electronics", sector: "Technology", category: "Computer Hardware and Accessories", parentIds: ["technology", "electronics", "manufacturing"], aliases: ["computer hardware", "computer", "computers", "pc", "pcs", "workstation", "keyboard", "computer accessories"], relatedTerms: ["gaming", "components", "processor", "graphics", "cooling", "memory", "storage", "peripherals"], productSignals: ["computer systems", "graphics hardware", "processors", "cooling", "memory", "storage", "chassis", "monitors", "peripherals", "keyboards"], serviceSignals: ["custom build", "configuration", "upgrade", "repair", "technical support"], audienceSignals: ["gamers", "creators", "professionals", "hardware enthusiasts", "business buyers"], businessModels: ["retail", "custom_build", "manufacturing", "repair"], capabilities: ["computer_hardware", "components", "technical_product", "performance", "specifications", "modular_hardware"], trustSignals: ["component compatibility", "clear specifications", "support and upgrade guidance"], visualSignals: ["chassis layers", "hardware modules", "cooling channels", "component architecture"] }),
  node({ id: "cybersecurity_networking", displayName: "Networking and Cybersecurity", sector: "Technology", category: "Computer Networking, Security, and Infrastructure", parentIds: ["technology", "it_services"], aliases: ["cybersecurity", "cyber security", "computer security", "networking", "network security", "information security"], relatedTerms: ["threat", "identity", "firewall", "cloud security", "zero trust"], productSignals: ["security assessments", "monitoring tools", "network systems"], serviceSignals: ["security consulting", "penetration testing", "monitoring", "incident response", "network design"], audienceSignals: ["organizations", "IT teams", "security leaders", "regulated businesses"], businessModels: ["consulting", "service", "saas"], capabilities: ["cybersecurity", "networking", "risk", "monitoring", "defensive_security"], trustSignals: ["authorized scope", "confidentiality", "clear remediation"], visualSignals: ["network topology", "security boundaries", "signal paths"] }),
  node({ id: "data_analytics", displayName: "Data and Analytics", sector: "Technology", category: "Analytics, Business Intelligence, and Data Platforms", parentIds: ["technology", "software"], aliases: ["data analytics", "analytics", "business intelligence", "data platform", "creator analytics"], relatedTerms: ["dashboard", "metrics", "insights", "reporting", "data pipeline"], productSignals: ["dashboards", "reports", "data pipelines", "measurement tools"], serviceSignals: ["analytics consulting", "data engineering", "reporting", "implementation"], audienceSignals: ["operators", "analysts", "creators", "business leaders"], businessModels: ["saas", "consulting", "service"], capabilities: ["analytics", "data", "reporting", "workflow", "software"], trustSignals: ["metric definitions", "data boundaries", "transparent methodology"], visualSignals: ["data cards", "signal flows", "metric layers"] }),
  node({ id: "creative_design_media", displayName: "Design, Media, Music, and Creative Services", sector: "Creative Industries", category: "Design, Photography, Music, Media, and Entertainment", parentIds: ["creative", "professional_services"], aliases: ["design studio", "creative studio", "photography studio", "photographer", "media company", "entertainment", "cinematography", "musical instrument", "musical instruments", "music business"], relatedTerms: ["portfolio", "editorial", "campaign", "film", "visual identity", "content", "guitar", "piano", "music"], productSignals: ["projects", "campaigns", "photographs", "films", "design systems", "instruments"], serviceSignals: ["design", "photography", "production", "creative direction", "cinematography"], audienceSignals: ["brands", "couples", "publishers", "creative clients", "musicians"], businessModels: ["service", "consulting", "retail"], capabilities: ["creative", "design", "media", "music", "storytelling", "portfolio"], trustSignals: ["selected work", "clear usage terms", "project process"], visualSignals: ["editorial frames", "image sequences", "art-directed layers", "sound waves"] }),
  node({ id: "education_training", displayName: "Education and Training", sector: "Education", category: "Schools, Training, and Online Learning", parentIds: ["education", "professional_services"], aliases: ["education", "school", "academy", "training", "online learning", "language school", "technical training"], relatedTerms: ["course", "lesson", "student", "instructor", "curriculum"], productSignals: ["courses", "learning paths", "classes", "resources"], serviceSignals: ["teaching", "training", "coaching", "certification preparation"], audienceSignals: ["students", "professionals", "beginners", "teams"], businessModels: ["education", "subscription", "service"], capabilities: ["education", "learning", "curriculum", "instruction", "community"], trustSignals: ["clear outcomes", "instructor context", "course structure"], visualSignals: ["learning paths", "lesson modules", "progress steps"] }),
  node({ id: "electronics_semiconductor", displayName: "Electronics and Semiconductors", sector: "Technology and Manufacturing", category: "Consumer Electronics, Components, and Semiconductors", parentIds: ["technology", "manufacturing"], aliases: ["electronics", "semiconductor", "consumer electronics", "television", "tv shop", "display technology"], relatedTerms: ["chip", "display", "oled", "qled", "sensor", "device"], productSignals: ["displays", "electronic devices", "components", "sensors", "audio equipment"], serviceSignals: ["installation", "device support", "technical sales"], audienceSignals: ["consumers", "installers", "engineers", "business buyers"], businessModels: ["retail", "manufacturing", "wholesale", "installation"], capabilities: ["electronics", "display", "components", "technical_product", "specifications"], trustSignals: ["warranty guidance", "clear specifications", "installation support"], visualSignals: ["display planes", "circuit layers", "component modules", "light surfaces"] }),
  node({ id: "energy_environment", displayName: "Energy and Environmental Services", sector: "Energy and Sustainability", category: "Energy, Renewables, Utilities, and Environmental Services", parentIds: ["energy", "industrial"], aliases: ["energy", "renewable energy", "solar", "wind energy", "environmental services", "utilities", "carbon accounting"], relatedTerms: ["power", "emissions", "climate", "efficiency", "storage"], productSignals: ["solar equipment", "energy systems", "storage systems", "monitoring tools"], serviceSignals: ["installation", "energy assessment", "environmental consulting", "carbon reporting"], audienceSignals: ["homeowners", "businesses", "industrial operators", "sustainability teams"], businessModels: ["installation", "service", "manufacturing", "saas", "consulting"], capabilities: ["energy", "renewables", "sustainability", "installation", "measurement"], trustSignals: ["site assessment", "performance assumptions", "service coverage"], visualSignals: ["energy flow", "solar arrays", "storage modules", "environmental systems"] }),
  node({ id: "engineering_industrial", displayName: "Engineering and Industrial Systems", sector: "Industrial and Engineering", category: "Industrial Machinery, Equipment, and Engineering", parentIds: ["industrial", "manufacturing"], aliases: ["engineering", "industrial machinery", "industrial equipment", "construction equipment", "machinery"], relatedTerms: ["fabrication", "automation", "production line", "mechanical", "equipment"], productSignals: ["industrial machines", "equipment", "production systems", "components", "tools"], serviceSignals: ["engineering", "maintenance", "installation", "commissioning", "technical support"], audienceSignals: ["manufacturers", "plant operators", "contractors", "engineering teams"], businessModels: ["manufacturing", "wholesale", "installation", "service"], capabilities: ["industrial", "engineering", "equipment", "mechanical_product", "technical_product"], trustSignals: ["technical specifications", "serviceability", "operating guidance"], visualSignals: ["machine assemblies", "mechanical layers", "structural frames"] }),
  node({ id: "fashion_textiles", displayName: "Fashion and Textiles", sector: "Consumer Products and Manufacturing", category: "Apparel, Textiles, Jewelry, and Accessories", parentIds: ["retail", "manufacturing", "design"], aliases: ["fashion", "clothing", "textiles", "apparel", "jewelry", "footwear"], relatedTerms: ["fabric", "garment", "collection", "handmade", "luxury", "baby clothing"], productSignals: ["garments", "fabrics", "jewelry", "accessories", "collections"], serviceSignals: ["custom design", "alteration", "styling", "textile production"], audienceSignals: ["shoppers", "collectors", "families", "design buyers"], businessModels: ["retail", "manufacturing", "wholesale", "custom_build"], capabilities: ["fashion", "textiles", "materials", "craft", "product_showcase"], trustSignals: ["material details", "care guidance", "sizing or specification context"], visualSignals: ["fabric folds", "material layers", "jewel facets", "collection rhythm"] }),
  node({ id: "food_beverage", displayName: "Food and Beverage", sector: "Food, Beverage, and Hospitality", category: "Restaurants, Bakeries, Catering, and Specialty Food", parentIds: ["hospitality", "consumer_products"], aliases: ["food", "restaurant", "bakery", "cafe", "coffee roastery", "catering", "beverage"], relatedTerms: ["menu", "roast", "ingredients", "dining", "vegan", "brew"], productSignals: ["menu items", "baked goods", "coffee beans", "drinks", "food packages"], serviceSignals: ["dining", "catering", "delivery", "events", "wholesale supply"], audienceSignals: ["diners", "coffee drinkers", "families", "event organizers"], businessModels: ["hospitality", "retail", "service", "wholesale"], capabilities: ["food", "beverage", "hospitality", "craft", "menu"], trustSignals: ["ingredient context", "dietary guidance", "service information"], visualSignals: ["ingredient forms", "roast tones", "table composition", "craft process"] }),
  node({ id: "government_nonprofit", displayName: "Government and Non-Profit", sector: "Public and Social Impact", category: "Government, Associations, and Non-Profit Organizations", parentIds: ["public_sector", "social_impact"], aliases: ["government", "non-profit", "nonprofit", "charity", "association", "ngo"], relatedTerms: ["public service", "community", "program", "mission", "policy"], productSignals: ["programs", "resources", "reports", "community initiatives"], serviceSignals: ["public services", "advocacy", "community support", "grant programs"], audienceSignals: ["residents", "members", "donors", "communities"], businessModels: ["service"], capabilities: ["public_service", "community", "programs", "transparency"], trustSignals: ["governance", "clear eligibility", "public reporting"], visualSignals: ["community networks", "program pathways", "public information hierarchy"] }),
  node({ id: "healthcare_medical", displayName: "Healthcare and Medical Services", sector: "Healthcare and Life Sciences", category: "Clinics, Therapy, Laboratories, and Medical Services", parentIds: ["healthcare", "professional_services"], aliases: ["healthcare", "medical", "clinic", "dental", "physical therapy", "rehabilitation", "medical laboratory"], relatedTerms: ["patient", "treatment", "diagnostic", "therapy", "care"], productSignals: ["care programs", "diagnostic services", "treatment information"], serviceSignals: ["consultation", "treatment", "therapy", "testing", "preventive care"], audienceSignals: ["patients", "families", "referring professionals"], businessModels: ["healthcare", "professional_practice", "service"], capabilities: ["healthcare", "care", "diagnostics", "appointments", "professional_practice"], trustSignals: ["qualified care", "privacy", "clear escalation guidance"], visualSignals: ["care pathways", "calm clinical space", "diagnostic layers"] }),
  node({ id: "hospitality_tourism", displayName: "Hospitality and Tourism", sector: "Travel and Hospitality", category: "Hotels, Tourism, Events, and Guest Services", parentIds: ["hospitality", "consumer_services"], aliases: ["hotel", "hospitality", "tourism", "travel agency", "guesthouse", "resort"], relatedTerms: ["stay", "destination", "guest", "itinerary", "booking"], productSignals: ["rooms", "packages", "itineraries", "experiences"], serviceSignals: ["accommodation", "trip planning", "guest support", "events"], audienceSignals: ["travelers", "families", "business guests", "tour groups"], businessModels: ["hospitality", "service", "rental"], capabilities: ["hospitality", "travel", "booking", "guest_experience"], trustSignals: ["booking terms", "location context", "guest support"], visualSignals: ["destination layers", "room stories", "route maps"] }),
  node({ id: "human_resources", displayName: "Human Resources and Recruitment", sector: "Business Services", category: "Recruitment, HR, and Workforce Services", parentIds: ["professional_services", "software"], aliases: ["human resources", "hr", "recruitment", "staffing", "talent"], relatedTerms: ["hiring", "workforce", "employee", "candidate", "payroll"], productSignals: ["job listings", "candidate tools", "workforce dashboards"], serviceSignals: ["recruitment", "HR consulting", "staffing", "training"], audienceSignals: ["employers", "candidates", "HR teams"], businessModels: ["service", "consulting", "saas"], capabilities: ["workforce", "recruitment", "people_operations", "workflow"], trustSignals: ["process clarity", "privacy", "fair hiring context"], visualSignals: ["candidate pipelines", "team networks", "process cards"] }),
  node({ id: "it_software_saas", displayName: "Software, SaaS, and IT Services", sector: "Technology", category: "Software Products, Platforms, and IT Services", parentIds: ["technology", "professional_services"], aliases: ["software", "saas", "platform", "IT services", "technology consultancy", "app", "AI agent consultancy", "spatial computing", "immersive computing", "XR studio"], relatedTerms: ["workflow", "automation", "cloud", "integration", "dashboard", "AI-powered", "interactive software", "3D interface"], productSignals: ["software platform", "dashboards", "automation tools", "integrations", "workflows"], serviceSignals: ["software delivery", "implementation", "IT support", "consulting", "integration"], audienceSignals: ["teams", "operators", "founders", "businesses"], businessModels: ["saas", "subscription", "consulting", "service"], capabilities: ["software", "saas", "workflow", "automation", "integration"], trustSignals: ["clear feature boundaries", "data handling context", "implementation path"], visualSignals: ["interface cards", "workflow paths", "system layers"] }),
  node({ id: "legal_professional", displayName: "Legal and Professional Services", sector: "Professional Services", category: "Legal Practices and Advisory Services", parentIds: ["professional_services"], aliases: ["legal", "law firm", "lawyer", "attorney", "legal consultancy"], relatedTerms: ["contract", "dispute", "compliance", "advisory", "practice"], productSignals: ["practice areas", "legal resources", "engagement information"], serviceSignals: ["legal consultation", "contract review", "dispute support", "compliance guidance"], audienceSignals: ["individuals", "businesses", "organizations"], businessModels: ["professional_practice", "consulting", "service"], capabilities: ["legal", "advisory", "professional_practice", "confidentiality"], trustSignals: ["jurisdiction boundaries", "confidentiality", "qualified counsel"], visualSignals: ["structured documents", "measured editorial hierarchy", "institutional forms"] }),
  node({ id: "logistics_warehousing", displayName: "Logistics and Warehousing", sector: "Transportation and Supply Chain", category: "Logistics, Storage, Distribution, and Cold Chain", parentIds: ["transportation", "industrial"], aliases: ["logistics", "warehousing", "warehouse", "cold storage", "shipping", "freight"], relatedTerms: ["distribution", "supply chain", "inventory", "delivery", "fleet"], productSignals: ["storage capacity", "distribution services", "tracking systems", "cold-chain equipment"], serviceSignals: ["storage", "fulfillment", "transport", "cold-chain handling", "distribution"], audienceSignals: ["manufacturers", "retailers", "exporters", "food businesses"], businessModels: ["service", "rental", "wholesale"], capabilities: ["logistics", "storage", "distribution", "operations", "cold_chain"], trustSignals: ["handling standards", "service coverage", "capacity context"], visualSignals: ["route networks", "storage grids", "cold-chain flow"] }),
  node({ id: "manufacturing_materials", displayName: "Manufacturing and Materials", sector: "Industrial and Manufacturing", category: "Manufacturing, Fabrication, Packaging, and Materials", parentIds: ["industrial"], aliases: ["manufacturing", "manufacturer", "fabrication", "metal fabrication", "packaging manufacturing", "factory"], relatedTerms: ["production", "materials", "assembly", "quality", "industrial"], productSignals: ["manufactured products", "components", "packaging", "fabricated parts", "materials"], serviceSignals: ["production", "fabrication", "contract manufacturing", "quality support"], audienceSignals: ["industrial buyers", "brands", "engineers", "procurement teams"], businessModels: ["manufacturing", "wholesale", "custom_build"], capabilities: ["manufacturing", "materials", "production", "quality", "technical_product"], trustSignals: ["material specifications", "process capability", "quality controls"], visualSignals: ["production layers", "material sheets", "assembly modules"] }),
  node({ id: "natural_resources", displayName: "Mining, Oil, Gas, and Natural Resources", sector: "Energy and Natural Resources", category: "Extraction, Processing, and Resource Services", parentIds: ["energy", "industrial"], aliases: ["mining", "oil and gas", "petroleum", "natural resources", "quarry"], relatedTerms: ["extraction", "processing", "field operations", "drilling"], productSignals: ["resource products", "field equipment", "processed materials"], serviceSignals: ["field services", "engineering", "processing", "inspection"], audienceSignals: ["operators", "industrial buyers", "engineering teams"], businessModels: ["manufacturing", "service", "wholesale"], capabilities: ["resources", "industrial", "field_operations", "engineering"], trustSignals: ["safety systems", "operating scope", "environmental context"], visualSignals: ["geological layers", "field systems", "processing paths"] }),
  node({ id: "real_estate_property", displayName: "Real Estate and Property", sector: "Built Environment", category: "Brokerage, Leasing, Development, and Property Services", parentIds: ["built_environment", "professional_services"], aliases: ["real estate", "property", "brokerage", "commercial leasing", "property leasing", "realtor"], relatedTerms: ["listing", "home", "commercial property", "development", "tenant"], productSignals: ["properties", "listings", "developments", "leasing options"], serviceSignals: ["brokerage", "leasing", "property management", "viewings"], audienceSignals: ["buyers", "sellers", "tenants", "investors"], businessModels: ["service", "professional_practice", "marketplace", "rental"], capabilities: ["property", "listings", "spatial", "brokerage"], trustSignals: ["listing status", "local context", "viewing confirmation"], visualSignals: ["property volumes", "site plans", "location layers"] }),
  node({ id: "retail_wholesale", displayName: "Retail and Wholesale", sector: "Commerce", category: "Product Retail, Wholesale, and Marketplaces", parentIds: ["commerce", "consumer_products"], aliases: ["retail", "store", "shop", "wholesale", "marketplace", "ecommerce", "florist", "flower shop"], relatedTerms: ["products", "catalog", "collection", "delivery", "orders", "bouquet", "seasonal flowers"], productSignals: ["products", "collections", "categories", "accessories"], serviceSignals: ["retail guidance", "delivery", "wholesale supply", "customer support"], audienceSignals: ["shoppers", "buyers", "retail partners"], businessModels: ["retail", "wholesale", "marketplace"], capabilities: ["retail", "commerce", "product_showcase", "catalog"], trustSignals: ["product details", "delivery context", "returns guidance"], visualSignals: ["product groupings", "shelf rhythm", "category layers"] }),
  node({ id: "robotics_automation", displayName: "Robotics and Automation", sector: "Technology and Engineering", category: "Robotics, Automation, and Intelligent Equipment", parentIds: ["technology", "engineering", "manufacturing"], aliases: ["robotics", "robot", "automation", "industrial automation", "vertical farming robotics"], relatedTerms: ["sensors", "autonomous", "machine vision", "control system", "actuator"], productSignals: ["robotic systems", "sensors", "controllers", "automation equipment"], serviceSignals: ["automation integration", "robotics engineering", "maintenance", "commissioning"], audienceSignals: ["manufacturers", "farm operators", "engineering teams", "innovators"], businessModels: ["manufacturing", "custom_build", "installation", "service"], capabilities: ["robotics", "automation", "sensors", "control_systems", "technical_product"], trustSignals: ["operating boundaries", "integration plan", "maintenance support"], visualSignals: ["robot joints", "sensor arrays", "automation paths", "modular equipment"] }),
  node({ id: "sports_fitness", displayName: "Sports, Fitness, and Rehabilitation", sector: "Health, Recreation, and Sport", category: "Sports, Fitness, Coaching, and Rehabilitation", parentIds: ["healthcare", "consumer_services"], aliases: ["sports", "fitness", "gym", "sports rehabilitation", "physical training"], relatedTerms: ["training", "performance", "recovery", "coach", "movement"], productSignals: ["programs", "classes", "equipment", "recovery plans"], serviceSignals: ["coaching", "training", "rehabilitation", "classes"], audienceSignals: ["athletes", "members", "beginners", "patients"], businessModels: ["service", "subscription", "healthcare"], capabilities: ["fitness", "performance", "movement", "recovery"], trustSignals: ["qualified guidance", "program fit", "safety boundaries"], visualSignals: ["movement paths", "training intervals", "body mechanics"] }),
  node({ id: "telecommunications", displayName: "Telecommunications", sector: "Technology and Infrastructure", category: "Telecom Networks and Connectivity", parentIds: ["technology", "infrastructure"], aliases: ["telecommunications", "telecom", "internet provider", "connectivity", "mobile network"], relatedTerms: ["network", "fiber", "broadband", "signal", "coverage"], productSignals: ["connectivity plans", "network equipment", "communication services"], serviceSignals: ["internet service", "network installation", "support", "enterprise connectivity"], audienceSignals: ["households", "businesses", "network teams"], businessModels: ["subscription", "service", "installation"], capabilities: ["telecommunications", "connectivity", "networking", "infrastructure"], trustSignals: ["coverage context", "service terms", "support availability"], visualSignals: ["signal waves", "network towers", "connection paths"] }),
  node({ id: "consumer_home_services", displayName: "Consumer and Home Services", sector: "Consumer Services", category: "Home, Personal, Repair, and Local Services", parentIds: ["consumer_services"], aliases: ["consumer services", "home services", "pet grooming", "laundry service", "landscaping", "cleaning service", "repair workshop"], relatedTerms: ["appointment", "local", "service area", "maintenance", "grooming"], productSignals: ["service packages", "care options", "maintenance plans"], serviceSignals: ["grooming", "cleaning", "laundry", "landscaping", "repair", "maintenance"], audienceSignals: ["households", "pet owners", "local customers", "property managers"], businessModels: ["service", "repair", "subscription"], capabilities: ["local_service", "care", "maintenance", "booking"], trustSignals: ["service area", "clear estimates", "care standards"], visualSignals: ["before-and-after sequence", "service steps", "care details"] }),
  node({ id: "veterinary_animal", displayName: "Veterinary and Animal Services", sector: "Healthcare and Consumer Services", category: "Veterinary Care and Animal Services", parentIds: ["healthcare", "consumer_services"], aliases: ["veterinary", "veterinarian", "vet clinic", "animal hospital", "pet clinic"], relatedTerms: ["pet", "animal care", "vaccination", "wellness", "surgery"], productSignals: ["care programs", "wellness plans", "pet resources"], serviceSignals: ["consultation", "vaccination", "diagnostics", "preventive care"], audienceSignals: ["pet owners", "families", "animal caregivers"], businessModels: ["healthcare", "professional_practice", "service"], capabilities: ["veterinary", "animal_care", "healthcare", "appointments"], trustSignals: ["qualified veterinary care", "emergency boundaries", "clear appointment guidance"], visualSignals: ["care pathways", "animal silhouettes", "calm clinical forms"] })
];

export function getUniversalIndustryNode(id: string | null | undefined) {
  if (!id) return null;
  return WEBSITE_INDUSTRY_CATALOG.find((candidate) => candidate.id === id) ?? null;
}
